//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 黄石申请单接收.JhCrisisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="JhCrisisService.CRITICALVALUESBSSoap")]
    public interface CRITICALVALUESBSSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JHIP.CRITICALVALUES.BS.CRITICALVALUESBS.JHEmrSynchroExeJhCriti" +
            "calValues", ReplyAction="*")]
        黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesResponse JHEmrSynchroExeJhCriticalValues(黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JHIP.CRITICALVALUES.BS.CRITICALVALUESBS.JHEmrSynchroExeThirdPa" +
            "rtyData", ReplyAction="*")]
        黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataResponse JHEmrSynchroExeThirdPartyData(黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHEmrSynchroExeJhCriticalValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHEmrSynchroExeJhCriticalValues", Namespace="http://tempuri.org", Order=0)]
        public 黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequestBody Body;
        
        public JHEmrSynchroExeJhCriticalValuesRequest() {
        }
        
        public JHEmrSynchroExeJhCriticalValuesRequest(黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JHEmrSynchroExeJhCriticalValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public JHEmrSynchroExeJhCriticalValuesRequestBody() {
        }
        
        public JHEmrSynchroExeJhCriticalValuesRequestBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHEmrSynchroExeJhCriticalValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHEmrSynchroExeJhCriticalValuesResponse", Namespace="http://tempuri.org", Order=0)]
        public 黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesResponseBody Body;
        
        public JHEmrSynchroExeJhCriticalValuesResponse() {
        }
        
        public JHEmrSynchroExeJhCriticalValuesResponse(黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JHEmrSynchroExeJhCriticalValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] JHEmrSynchroExeJhCriticalValuesResult;
        
        public JHEmrSynchroExeJhCriticalValuesResponseBody() {
        }
        
        public JHEmrSynchroExeJhCriticalValuesResponseBody(byte[] JHEmrSynchroExeJhCriticalValuesResult) {
            this.JHEmrSynchroExeJhCriticalValuesResult = JHEmrSynchroExeJhCriticalValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHEmrSynchroExeThirdPartyDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHEmrSynchroExeThirdPartyData", Namespace="http://tempuri.org", Order=0)]
        public 黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequestBody Body;
        
        public JHEmrSynchroExeThirdPartyDataRequest() {
        }
        
        public JHEmrSynchroExeThirdPartyDataRequest(黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JHEmrSynchroExeThirdPartyDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public JHEmrSynchroExeThirdPartyDataRequestBody() {
        }
        
        public JHEmrSynchroExeThirdPartyDataRequestBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHEmrSynchroExeThirdPartyDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHEmrSynchroExeThirdPartyDataResponse", Namespace="http://tempuri.org", Order=0)]
        public 黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataResponseBody Body;
        
        public JHEmrSynchroExeThirdPartyDataResponse() {
        }
        
        public JHEmrSynchroExeThirdPartyDataResponse(黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JHEmrSynchroExeThirdPartyDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] JHEmrSynchroExeThirdPartyDataResult;
        
        public JHEmrSynchroExeThirdPartyDataResponseBody() {
        }
        
        public JHEmrSynchroExeThirdPartyDataResponseBody(byte[] JHEmrSynchroExeThirdPartyDataResult) {
            this.JHEmrSynchroExeThirdPartyDataResult = JHEmrSynchroExeThirdPartyDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRITICALVALUESBSSoapChannel : 黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRITICALVALUESBSSoapClient : System.ServiceModel.ClientBase<黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap>, 黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap {
        
        public CRITICALVALUESBSSoapClient() {
        }
        
        public CRITICALVALUESBSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRITICALVALUESBSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRITICALVALUESBSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRITICALVALUESBSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesResponse 黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap.JHEmrSynchroExeJhCriticalValues(黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequest request) {
            return base.Channel.JHEmrSynchroExeJhCriticalValues(request);
        }
        
        public byte[] JHEmrSynchroExeJhCriticalValues(string pInput) {
            黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequest inValue = new 黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequest();
            inValue.Body = new 黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesRequestBody();
            inValue.Body.pInput = pInput;
            黄石申请单接收.JhCrisisService.JHEmrSynchroExeJhCriticalValuesResponse retVal = ((黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap)(this)).JHEmrSynchroExeJhCriticalValues(inValue);
            return retVal.Body.JHEmrSynchroExeJhCriticalValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataResponse 黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap.JHEmrSynchroExeThirdPartyData(黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequest request) {
            return base.Channel.JHEmrSynchroExeThirdPartyData(request);
        }
        
        public byte[] JHEmrSynchroExeThirdPartyData(string pInput) {
            黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequest inValue = new 黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequest();
            inValue.Body = new 黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataRequestBody();
            inValue.Body.pInput = pInput;
            黄石申请单接收.JhCrisisService.JHEmrSynchroExeThirdPartyDataResponse retVal = ((黄石申请单接收.JhCrisisService.CRITICALVALUESBSSoap)(this)).JHEmrSynchroExeThirdPartyData(inValue);
            return retVal.Body.JHEmrSynchroExeThirdPartyDataResult;
        }
    }
}
