//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class department
    {
        public int F_ID { get; set; }
        public string deptCode { get; set; }
        public string deptName { get; set; }
        public string deptType { get; set; }
        public string parentID { get; set; }
        public string deptLevel { get; set; }
        public string nDesc { get; set; }
        public string validState { get; set; }
        public string pefDeptHr { get; set; }
        public string pefDeptHis { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
    }
}
