//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class doctor
    {
        public int F_ID { get; set; }
        public string name { get; set; }
        public string ortherName { get; set; }
        public string departments { get; set; }
        public string ward { get; set; }
        public string performance { get; set; }
        public string deptidentification { get; set; }
        public string status { get; set; }
        public string employeeNo { get; set; }
        public string employeeType { get; set; }
        public string sex { get; set; }
        public string birthday { get; set; }
        public string age { get; set; }
        public string nation { get; set; }
        public string IDNo { get; set; }
        public string politicalStatus { get; set; }
        public string entrydate { get; set; }
        public string currentduty { get; set; }
        public string dutylevel { get; set; }
        public string otherduty { get; set; }
        public string cellphone { get; set; }
        public string telephone { get; set; }
        public string QQ { get; set; }
        public string email { get; set; }
        public string oldemployeeNo { get; set; }
        public string password { get; set; }
        public string certificateNo { get; set; }
        public string firstcertificateTime { get; set; }
        public string certificateTimeTo { get; set; }
        public string changedcertificateTime { get; set; }
        public string lastcertificatecompany { get; set; }
        public string bankaccount { get; set; }
    }
}
