//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class examrecord
    {
        public string F_BRBH { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string BUSINESS_ID { get; set; }
        public string DATAGENERATE_DATE { get; set; }
        public string AP08_10_002_00 { get; set; }
        public string AP01_00_022_00 { get; set; }
        public string AP04_50_057_00 { get; set; }
        public string AP04_50_056_00 { get; set; }
        public string AP06_00_048_03 { get; set; }
        public string DE04_30_018_00 { get; set; }
        public string AP04_30_018_01 { get; set; }
        public string DE04_30_019_00 { get; set; }
        public string DE04_30_020_00 { get; set; }
        public string AP02_01_115_02 { get; set; }
        public string AP02_01_115_01 { get; set; }
        public string AP04_30_059_00 { get; set; }
        public string DE04_30_015_00 { get; set; }
        public string DE04_30_017_00 { get; set; }
        public string AP04_30_046_00 { get; set; }
        public string AP08_10_025_05 { get; set; }
        public string AP08_10_025_09 { get; set; }
        public string AP08_10_026_11 { get; set; }
        public string AP08_10_013_06 { get; set; }
    }
}
