//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MDM_CYC
    {
        public int F_ID { get; set; }
        public string dictType { get; set; }
        public string dictTypeDesc { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public string valid { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
    }
}
