//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BB
    {
        public int F_ID { get; set; }
        public string F_BBTMH { get; set; }
        public string F_BLH { get; set; }
        public string F_SQXH { get; set; }
        public string F_BBXH { get; set; }
        public string F_BBMC { get; set; }
        public string F_CQBW { get; set; }
        public string F_BZ { get; set; }
        public string F_LTSJ { get; set; }
        public string F_GDSJ { get; set; }
        public string F_JSSJ { get; set; }
        public string F_JSY { get; set; }
        public string F_BBZT { get; set; }
        public string F_BBPJ { get; set; }
        public string F_PJR { get; set; }
        public string F_PJSJ { get; set; }
    }
}
