//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BDBG
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public Nullable<int> F_BD_BGXH { get; set; }
        public string F_BD_BGYS { get; set; }
        public string F_BD_SHYS { get; set; }
        public string F_BD_BGRQ { get; set; }
        public string F_BD_BGZT { get; set; }
        public string F_BDZD { get; set; }
        public string F_BD_ZPR { get; set; }
        public string F_BD_SDRQ { get; set; }
        public string F_BD_QCYS { get; set; }
        public string F_BD_CFYY { get; set; }
        public string F_BD_ZPS { get; set; }
        public string F_BD_BZ { get; set; }
        public string F_BD_FZYS { get; set; }
        public string F_BD_DYZT { get; set; }
        public string F_BD_QSB_DYZT { get; set; }
        public string F_BD_BGWZ { get; set; }
        public string F_BD_BGWZ_QRSJ { get; set; }
        public string F_BD_BGWZ_QRCZY { get; set; }
        public string F_ZPSJ { get; set; }
        public string F_LTSJ { get; set; }
        public string F_ZPKSSJ { get; set; }
        public string F_BD_FBSJ { get; set; }
        public string F_BD_FBYS { get; set; }
        public string F_BD_BBMC { get; set; }
        public string F_BD_RYSJ { get; set; }
        public string F_BD_SPARE5 { get; set; }
    }
}
