//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BG_ZLPJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_BGZL { get; set; }
        public string F_BGZL_YYFX { get; set; }
        public string F_BGZLPJ_PJR { get; set; }
        public string F_BGZLPJ_PJSJ { get; set; }
    }
}
