//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BG_PDF
    {
        public int F_ID { get; set; }
        public string F_BLBH { get; set; }
        public string F_BLH { get; set; }
        public string F_BGLX { get; set; }
        public string F_BGXH { get; set; }
        public string F_ML { get; set; }
        public string F_FILENAME { get; set; }
        public string F_JPG_errmsg { get; set; }
        public string F_BZ { get; set; }
        public string F_filePath { get; set; }
        public string F_pdfpath { get; set; }
        public string F_PDFLX { get; set; }
    }
}
