//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BGFF
    {
        public long F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_JSSJ { get; set; }
        public string F_JSZ { get; set; }
        public string F_FFSJ { get; set; }
        public string F_FFZ { get; set; }
        public string F_ZT { get; set; }
        public string F_BZ { get; set; }
        public string F_BGLX { get; set; }
        public string F_bgxh { get; set; }
        public string F_DXFSSJ { get; set; }
        public string F_DXFSBZ { get; set; }
        public string F_DXZT { get; set; }
        public string F_BLBH { get; set; }
    }
}
