//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BGGD
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_TKGDZT { get; set; }
        public string F_TKGDSM { get; set; }
        public string F_TKGDSJ { get; set; }
        public string F_PACSGDZT { get; set; }
        public string F_PACSGDSM { get; set; }
        public string F_PACSGDSJ { get; set; }
        public string F_YLGDZT { get; set; }
        public string F_YLGDSM { get; set; }
        public string F_YLGDSJ { get; set; }
        public Nullable<bool> f_TKflag { get; set; }
        public Nullable<int> f_tkgdcs { get; set; }
    }
}
