//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BJWTC
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXH { get; set; }
        public string F_BJWTC_MC { get; set; }
        public string F_BJWTC_NR { get; set; }
        public string F_TJYZ_FL { get; set; }
    }
}
