//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BJW_CYC
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXH { get; set; }
        public string F_BJW_MC { get; set; }
        public string F_TJYZ_FL { get; set; }
        public string F_BJW_SM { get; set; }
        public string F_DAKO { get; set; }
        public string F_LEICA { get; set; }
        public string F_ROCHE { get; set; }
        public string F_PATHCOM { get; set; }
        public string F_BXCYC { get; set; }
        public int F_SFKZ { get; set; }
        public string F_BIOCARE { get; set; }
        public string F_KFSSB { get; set; }
    }
}
