//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_BLK_CS
    {
        public int F_ID { get; set; }
        public string F_BLKMC { get; set; }
        public string F_BGGS { get; set; }
        public string F_TABID { get; set; }
        public string F_BBLC_FL { get; set; }
        public string F_BSM { get; set; }
        public string F_BLHMC { get; set; }
        public int F_SF { get; set; }
        public int F_ZPS { get; set; }
        public int F_TBSID { get; set; }
        public string F_TBSMC { get; set; }
        public string F_DJBGS { get; set; }
        public string F_BBLX { get; set; }
        public string F_BLHWS { get; set; }
    }
}
