//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_jcxx_fs
    {
        public int F_id { get; set; }
        public string F_BLBH { get; set; }
        public string F_blh { get; set; }
        public string F_bglx { get; set; }
        public string F_bgxh { get; set; }
        public string F_bgzt { get; set; }
        public string F_fszt { get; set; }
        public string F_jssj { get; set; }
        public string F_fssj { get; set; }
        public Nullable<int> F_fscs { get; set; }
        public string F_bz { get; set; }
        public string F_isjpg { get; set; }
        public string F_JPG_errmsg { get; set; }
        public string f_ispdf { get; set; }
        public string GUID { get; set; }
    }
}
