//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_LGI_WJZ
    {
        public string ID { get; set; }
        public string F_BLH { get; set; }
        public string F_LXBM { get; set; }
        public string F_LXMC { get; set; }
        public string F_SM { get; set; }
        public string F_SBRXM { get; set; }
        public string F_SHRXM { get; set; }
        public Nullable<System.DateTime> F_SBSJ { get; set; }
        public Nullable<int> F_LCCLZT { get; set; }
        public Nullable<System.DateTime> F_LCCLSZ { get; set; }
    }
}
