//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_PATHCOM_TJYZ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_LKH { get; set; }
        public string F_YZH { get; set; }
        public string F_QPTMH { get; set; }
        public string F_TJH { get; set; }
        public string F_BJW { get; set; }
        public string F_ZXZT { get; set; }
        public string F_CZY { get; set; }
        public string F_CZSJ { get; set; }
        public string F_BZ { get; set; }
    }
}
