//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_QP_YDY
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_QCXH { get; set; }
        public string F_QPTMH { get; set; }
        public string F_QPBH { get; set; }
        public string F_QPSM { get; set; }
        public string F_CZY { get; set; }
        public string F_QPSJ { get; set; }
        public string F_DYZT { get; set; }
    }
}
