//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SF_JEZK
    {
        public int F_ID { get; set; }
        public string F_SJDW { get; set; }
        public double F_ZXJE { get; set; }
        public double F_ZDJE { get; set; }
        public double F_ZK { get; set; }
        public string F_BZ { get; set; }
    }
}
