//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SF_XM
    {
        public int F_ID { get; set; }
        public string F_SFXMDM { get; set; }
        public string F_SFXMMC { get; set; }
        public string F_SFXMSM { get; set; }
        public string F_DW { get; set; }
        public Nullable<double> F_DJ { get; set; }
        public string F_BZ { get; set; }
        public string F_ZJC1 { get; set; }
        public string F_ZJC2 { get; set; }
        public Nullable<int> F_PXH { get; set; }
    }
}
