//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SF
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_BRBH { get; set; }
        public string F_SQXH { get; set; }
        public string F_MZH { get; set; }
        public string F_ZYH { get; set; }
        public string F_SFXMDM { get; set; }
        public string F_SFXMMC { get; set; }
        public string F_DW { get; set; }
        public Nullable<double> F_DJ { get; set; }
        public Nullable<int> F_SL { get; set; }
        public Nullable<double> F_ZJ { get; set; }
        public string F_SFY { get; set; }
        public string F_SFRQ { get; set; }
        public string F_SFZT { get; set; }
        public string F_FPH { get; set; }
        public string F_XLH { get; set; }
        public string F_FYLX { get; set; }
        public string F_YZID { get; set; }
    }
}
