//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SJ_CKB
    {
        public int F_id { get; set; }
        public string F_ckdh { get; set; }
        public string F_ckrq { get; set; }
        public string F_lkdh { get; set; }
        public string F_cksl { get; set; }
        public string F_wlmc { get; set; }
        public string F_cklx { get; set; }
        public string F_check { get; set; }
        public string F_bz { get; set; }
        public string F_lybm { get; set; }
        public string F_lyr { get; set; }
        public string F_cky { get; set; }
        public string F_czy { get; set; }
    }
}
