//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SJ_WL
    {
        public int F_id { get; set; }
        public string F_wlmc { get; set; }
        public string F_wlz { get; set; }
        public string F_wlm { get; set; }
        public string F_tym { get; set; }
        public string F_bzdw { get; set; }
        public string F_gg { get; set; }
        public string F_dw { get; set; }
        public string F_dj { get; set; }
        public string F_zdkc { get; set; }
        public string F_yxq { get; set; }
        public string F_zt { get; set; }
        public string F_zd1 { get; set; }
        public string F_zd2 { get; set; }
        public string F_zd3 { get; set; }
        public string F_zd4 { get; set; }
        public string F_zd5 { get; set; }
        public string F_zd6 { get; set; }
        public string F_zD7 { get; set; }
        public string F_zd8 { get; set; }
        public string F_zd9 { get; set; }
        public string F_zd10 { get; set; }
        public string F_xh { get; set; }
        public string F_tsts { get; set; }
    }
}
