//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SJ_GYS
    {
        public int F_id { get; set; }
        public string F_gysid { get; set; }
        public string F_gysmc { get; set; }
        public string F_dz { get; set; }
        public string F_yzbm { get; set; }
        public string F_dh { get; set; }
        public string F_fax { get; set; }
        public string F_lxr { get; set; }
        public string F_email { get; set; }
        public string F_zy { get; set; }
        public string F_yddh { get; set; }
    }
}
