//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SQD_BBXX
    {
        public int F_ID { get; set; }
        public string F_XH { get; set; }
        public string F_SQXH { get; set; }
        public string F_YZH { get; set; }
        public string F_BBH { get; set; }
        public string F_TMH { get; set; }
        public string F_BBMC { get; set; }
        public string F_CQBW { get; set; }
        public string F_SL { get; set; }
        public string F_LTSJ { get; set; }
        public string F_GDSJ { get; set; }
        public string F_CYSJ { get; set; }
        public string F_SJSJ { get; set; }
        public string F_FJYBM { get; set; }
        public string F_FJYXM { get; set; }
        public string F_FJYTEL { get; set; }
        public string F_FJSJ { get; set; }
    }
}
