//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_SZQM
    {
        public string F_BLBH { get; set; }
        public string F_BLH { get; set; }
        public string F_BGLX { get; set; }
        public string F_BGXH { get; set; }
        public string F_CZY { get; set; }
        public string F_YW { get; set; }
        public string F_SignCert { get; set; }
        public string F_SignData { get; set; }
        public string F_QZRQ { get; set; }
    }
}
