//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_TBS_XSGS_TEXT
    {
        public int F_ID { get; set; }
        public Nullable<int> F_BG_ID { get; set; }
        public string F_SM { get; set; }
        public string F_TAG { get; set; }
        public Nullable<int> F_MAXLEGHT { get; set; }
        public Nullable<int> F_TXT_INDEX { get; set; }
        public string F_TEXT { get; set; }
        public Nullable<int> F_TAB_ID { get; set; }
        public Nullable<int> F_CX { get; set; }
        public Nullable<int> F_CY { get; set; }
        public Nullable<int> F_WIDTH { get; set; }
        public Nullable<int> F_HEIGHT { get; set; }
        public string F_ZT { get; set; }
        public Nullable<int> F_ZH { get; set; }
        public Nullable<int> F_COLOR { get; set; }
        public bool F_ISBOLD { get; set; }
        public bool F_ISITALIC { get; set; }
        public bool F_ISSK { get; set; }
        public bool F_ISUL { get; set; }
    }
}
