//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_XGYJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public Nullable<int> F_XH { get; set; }
        public string F_YSXM { get; set; }
        public string F_XGSJ { get; set; }
        public string F_XGYJ { get; set; }
        public string F_PJYS { get; set; }
        public string F_FPJG { get; set; }
    }
}
