//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_YH
    {
        public int F_ID { get; set; }
        public string F_YHM { get; set; }
        public string F_YHMC { get; set; }
        public string F_YHBH { get; set; }
        public Nullable<int> F_YHQX { get; set; }
        public string F_YHMM { get; set; }
        public string F_DLSJ { get; set; }
        public string F_SFZX { get; set; }
        public string F_ZXWZ { get; set; }
        public Nullable<int> F_ZXSC { get; set; }
        public string F_DXYS { get; set; }
        public string F_SFZH { get; set; }
        public string F_DHHM { get; set; }
        public string F_FJH { get; set; }
        public string F_CXTS { get; set; }
        public int F_DXFPYS { get; set; }
        public string F_YH_BY1 { get; set; }
        public string F_YH_BY2 { get; set; }
    }
}
