//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class TB
    {
        public string XM { get; set; }
        public string XB { get; set; }
        public string NL { get; set; }
        public string SJRQ { get; set; }
        public string BLH { get; set; }
        public string MZH { get; set; }
        public string ZYH { get; set; }
        public string SJYS { get; set; }
        public string BGYS { get; set; }
        public string SJYY { get; set; }
        public string SJKS { get; set; }
        public string BGRQ { get; set; }
        public string BLK { get; set; }
        public string BY3 { get; set; }
        public string BY5 { get; set; }
        public string BBZL { get; set; }
        public string GGXZD { get; set; }
        public string TBSZD { get; set; }
        public string BBZL1 { get; set; }
        public string BBZL2 { get; set; }
        public string BBZL3 { get; set; }
        public string WSW1 { get; set; }
        public string WSW2 { get; set; }
        public string WSW3 { get; set; }
        public string JSHJY { get; set; }
        public string ztfl { get; set; }
        public string JYFF { get; set; }
        public string l13 { get; set; }
        public string qtexzl { get; set; }
        public string bbzl4 { get; set; }
        public string bbzl5 { get; set; }
        public string wsw4 { get; set; }
    }
}
