//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_BDBG
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_ZYH { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_RYSJ { get; set; }
        public string F_BD_BGYS { get; set; }
        public string F_BD_FZYS { get; set; }
        public string F_BD_SHYS { get; set; }
        public string F_BD_BGRQ { get; set; }
        public string F_BD_BGZT { get; set; }
        public string F_BDZD { get; set; }
        public string F_MZH { get; set; }
    }
}
