//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_BDBG_HFZ_BDVIEW
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_ZYH { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_CH { get; set; }
        public string F_BBMC { get; set; }
        public string F_BLZD { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_XSBQ { get; set; }
        public string F_SJKS { get; set; }
    }
}
