//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_BM_DBM
    {
        public string F_BBLX { get; set; }
        public string F_BLK { get; set; }
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_QCXH { get; set; }
        public string F_ZZMC { get; set; }
        public string F_CKS { get; set; }
        public string F_QCYS { get; set; }
        public string F_QCRQ { get; set; }
        public string F_BMZT { get; set; }
        public string F_SM { get; set; }
        public string F_BZ { get; set; }
        public string F_SJZT { get; set; }
        public string F_JLY { get; set; }
        public string F_QCSJ { get; set; }
        public string F_HDZT { get; set; }
        public string F_HDR { get; set; }
        public string F_HDSJ { get; set; }
    }
}
