//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_brxx
    {
        public string f_unisbh { get; set; }
        public string f_sb { get; set; }
        public string f_unisb { get; set; }
        public string F_SBH { get; set; }
        public string F_JCH { get; set; }
        public string F_ZYH { get; set; }
        public string F_MZH { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_BQ { get; set; }
        public string F_CH { get; set; }
        public string F_SJKS { get; set; }
        public string F_SJRQ { get; set; }
        public string F_SJYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGYS { get; set; }
        public string F_BGBM { get; set; }
        public string f_bgzt { get; set; }
        public string f_bw { get; set; }
        public string f_bm { get; set; }
    }
}
