//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_PATHCOM_TJYZ
    {
        public int 序号 { get; set; }
        public string 病理号 { get; set; }
        public string 蜡块号 { get; set; }
        public string 特检号 { get; set; }
        public string 标记物 { get; set; }
        public string 执行状态 { get; set; }
        public string 操作员 { get; set; }
        public string 操作时间 { get; set; }
        public string 备注 { get; set; }
    }
}
