//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_PDF_TO_APP
    {
        public string blh { get; set; }
        public string jzlsh { get; set; }
        public string brwyh { get; set; }
        public string xm { get; set; }
        public string jclsh { get; set; }
        public string xxlx { get; set; }
        public string xxzlx { get; set; }
        public string xmid { get; set; }
        public string xmmc { get; set; }
        public string xmlj { get; set; }
        public string bgsjsj { get; set; }
        public string bgshsj { get; set; }
        public string bgys { get; set; }
        public string bglj { get; set; }
        public string bglx { get; set; }
    }
}
