//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_QP_TJYZ_ID
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_TJYZH { get; set; }
        public string F_YZLX { get; set; }
        public string F_LKH { get; set; }
        public string F_BJW { get; set; }
        public Nullable<int> F_SL { get; set; }
        public string F_BX { get; set; }
        public string F_QD { get; set; }
        public string F_BZ { get; set; }
        public string F_SQYS { get; set; }
        public string F_SQSJ { get; set; }
        public string F_YZZT { get; set; }
        public string F_ZXSJ { get; set; }
        public string F_ZXR { get; set; }
        public string F_DKRH { get; set; }
        public string F_LX { get; set; }
        public string F_CJ { get; set; }
        public string F_FF { get; set; }
        public string F_ZXSB { get; set; }
        public string F_FSSJ { get; set; }
        public string F_BLH2 { get; set; }
    }
}
