//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_TBS_XYLTJ
    {
        public string F_BLK { get; set; }
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_NL { get; set; }
        public string F_SDRQ { get; set; }
        public string F_BGRQ { get; set; }
        public string F_TBS_JYFF { get; set; }
        public string F_TBS_MPFX { get; set; }
        public string F_TBS_XBXM1 { get; set; }
        public string F_TBS_XBXM2 { get; set; }
        public string F_TBS_XBXM3 { get; set; }
        public string F_TBS_XBXM4 { get; set; }
        public string F_TBS_XBXM5 { get; set; }
        public string F_TBS_XBXM6 { get; set; }
        public string F_TBS_WSW1 { get; set; }
        public string F_TBS_WSW2 { get; set; }
        public string F_TBS_WSW3 { get; set; }
        public string F_TBS_WSW4 { get; set; }
        public string F_TBS_WSW5 { get; set; }
        public string F_TBS_WSW6 { get; set; }
        public string F_TBS_BDXM1 { get; set; }
        public string F_TBS_BDXM2 { get; set; }
        public string F_TBS_BDXM3 { get; set; }
        public string F_TBS_BDXM4 { get; set; }
        public string F_TBS_BDXM5 { get; set; }
        public string F_TBS_BDXM6 { get; set; }
        public string F_TBS_BBMYD { get; set; }
        public string F_TBS_YZCD { get; set; }
        public string F_TBS_ZGBL { get; set; }
        public string F_TBSZD { get; set; }
        public string F_TBS_BCYJ1 { get; set; }
        public string F_TBS_BCYJ2 { get; set; }
        public string F_TBS_XJRQ { get; set; }
        public string F_TBS_ZPR { get; set; }
        public string F_TBS_XBL { get; set; }
    }
}
