//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_TBS
    {
        public string XM { get; set; }
        public string XB { get; set; }
        public string NL { get; set; }
        public string SQXH { get; set; }
        public string BH { get; set; }
        public string KS { get; set; }
        public string QYRQ { get; set; }
        public string MYD { get; set; }
        public string XBL { get; set; }
        public string JGXB { get; set; }
        public string HSXB { get; set; }
        public string BDYJ { get; set; }
        public string DCGR { get; set; }
        public string NZGR { get; set; }
        public string HPV { get; set; }
        public string BZGR { get; set; }
        public string YJ1 { get; set; }
        public string YJ2 { get; set; }
        public string BGYS { get; set; }
        public string BGRQ { get; set; }
    }
}
