//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class V_TJ_JCXX
    {
        public string F_BLK { get; set; }
        public string F_JSY { get; set; }
        public string F_JLY { get; set; }
        public string F_SJYS { get; set; }
        public string F_SJKS { get; set; }
        public string F_SJDW { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_FZYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGLRY { get; set; }
        public Nullable<double> F_SF { get; set; }
        public string F_SFFH { get; set; }
        public string F_BD_SFFH { get; set; }
        public string F_RQ { get; set; }
        public string F_YL1 { get; set; }
    }
}
