//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace 黄石危急值回传.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CRITICALVALUESBSSoap", Namespace="http://tempuri.org")]
    public partial class CRITICALVALUESBS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback JHEmrSynchroExeJhCriticalValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback JHEmrSynchroExeThirdPartyDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CRITICALVALUESBS() {
            this.Url = global::黄石危急值回传.Properties.Settings.Default.黄石危急值回传_WebReference_CRITICALVALUESBS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event JHEmrSynchroExeJhCriticalValuesCompletedEventHandler JHEmrSynchroExeJhCriticalValuesCompleted;
        
        /// <remarks/>
        public event JHEmrSynchroExeThirdPartyDataCompletedEventHandler JHEmrSynchroExeThirdPartyDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/JHIP.CRITICALVALUES.BS.CRITICALVALUESBS.JHEmrSynchroExeJhCriti" +
            "calValues", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] JHEmrSynchroExeJhCriticalValues(string pInput) {
            object[] results = this.Invoke("JHEmrSynchroExeJhCriticalValues", new object[] {
                        pInput});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void JHEmrSynchroExeJhCriticalValuesAsync(string pInput) {
            this.JHEmrSynchroExeJhCriticalValuesAsync(pInput, null);
        }
        
        /// <remarks/>
        public void JHEmrSynchroExeJhCriticalValuesAsync(string pInput, object userState) {
            if ((this.JHEmrSynchroExeJhCriticalValuesOperationCompleted == null)) {
                this.JHEmrSynchroExeJhCriticalValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJHEmrSynchroExeJhCriticalValuesOperationCompleted);
            }
            this.InvokeAsync("JHEmrSynchroExeJhCriticalValues", new object[] {
                        pInput}, this.JHEmrSynchroExeJhCriticalValuesOperationCompleted, userState);
        }
        
        private void OnJHEmrSynchroExeJhCriticalValuesOperationCompleted(object arg) {
            if ((this.JHEmrSynchroExeJhCriticalValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JHEmrSynchroExeJhCriticalValuesCompleted(this, new JHEmrSynchroExeJhCriticalValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/JHIP.CRITICALVALUES.BS.CRITICALVALUESBS.JHEmrSynchroExeThirdPa" +
            "rtyData", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] JHEmrSynchroExeThirdPartyData(string pInput) {
            object[] results = this.Invoke("JHEmrSynchroExeThirdPartyData", new object[] {
                        pInput});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void JHEmrSynchroExeThirdPartyDataAsync(string pInput) {
            this.JHEmrSynchroExeThirdPartyDataAsync(pInput, null);
        }
        
        /// <remarks/>
        public void JHEmrSynchroExeThirdPartyDataAsync(string pInput, object userState) {
            if ((this.JHEmrSynchroExeThirdPartyDataOperationCompleted == null)) {
                this.JHEmrSynchroExeThirdPartyDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJHEmrSynchroExeThirdPartyDataOperationCompleted);
            }
            this.InvokeAsync("JHEmrSynchroExeThirdPartyData", new object[] {
                        pInput}, this.JHEmrSynchroExeThirdPartyDataOperationCompleted, userState);
        }
        
        private void OnJHEmrSynchroExeThirdPartyDataOperationCompleted(object arg) {
            if ((this.JHEmrSynchroExeThirdPartyDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JHEmrSynchroExeThirdPartyDataCompleted(this, new JHEmrSynchroExeThirdPartyDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void JHEmrSynchroExeJhCriticalValuesCompletedEventHandler(object sender, JHEmrSynchroExeJhCriticalValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JHEmrSynchroExeJhCriticalValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JHEmrSynchroExeJhCriticalValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void JHEmrSynchroExeThirdPartyDataCompletedEventHandler(object sender, JHEmrSynchroExeThirdPartyDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JHEmrSynchroExeThirdPartyDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JHEmrSynchroExeThirdPartyDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591